#pragma once



#define CMD_MANAGER_DIALOG      0x9
#define PROCESS_MANAGER_DIALOG  0x10  //进程对话框刷新标志
#define WINDOW_MANAGER_DIALOG   0x11  //窗口管理
#define REMOTE_CONTROLL_DIALOG  0x12  //远程控制
#define FILE_MANAGER_DIALOG     0x13
#define AUDIO_MANAGER_DIALOG    0x14
#define VIDEO_MANAGER_DIALOG    0x15
#define SERVICE_MANAGER_DIALOG  0x16
#define REGISTER_MANAGER_DIALOG 0x17    

#define UM_CLIENT_LOGIN                 WM_USER+1000
#define UM_OPEN_REMOTE_MESSAGE_DIALOG   WM_USER+1005
#define UM_OPEN_CMD_MANAGER_DIALOG      WM_USER+1006
#define UM_OPEN_PROCESS_MANAGER_DIALOG  WM_USER+1007
#define UM_OPEN_WINDOW_MANAGER_DIALOG   WM_USER+1008
#define UM_OPEN_REMOTE_CONTROLL_DIALOG  WM_USER+1009
#define UM_OPEN_FILE_MANAGER_DIALOG     WM_USER+1010
#define UM_OPEN_AUDIO_MANAGER_DIALOG    WM_USER+1011
#define UM_OPEN_VIDEO_MANAGER_DIALOG    WM_USER+1012
#define UM_OPEN_SERVICE_MANAGER_DIALOG  WM_USER+1013
#define UM_OPEN_REGISTER_MANAGER_DIALOG WM_USER+1014

#pragma pack(1)
typedef struct _LOGIN_INFORMATION_
{
	BYTE            IsToken;                  //信息头部
	OSVERSIONINFOEX OsVersionInfoEx;          //版本信息
	char ProcessorNameString[MAX_PATH];   //cpu主频
	IN_ADDR         ClientAddress;        //储存32位的IPv4的地址数据结构
	char            HostName[MAX_PATH];   //主机名
	BOOL            IsWebCameraExist;         //是否有摄像头
	DWORD           WebSpeed;                 //网速
}LOGIN_INFORMATION, *PLOGIN_INFORMATION;

#pragma pack(1)
typedef struct _PROCESS_ITEM_INFORMATION_
{
	HANDLE ProcessID;
	char   ProcessImageName[MAX_PATH];
	char   ProcessFullPath[MAX_PATH];
	char   IsWow64Process[20];
}PROCESS_ITEM_INFORMATION, *PPROCESS_ITEM_INFORMATION;


enum
{
	//文件传输方式
	TRANSFER_MODE_NORMAL = 0x00,  //一般
	TRANSFER_MODE_ADDITION,       //追加
	TRANSFER_MODE_ADDITION_ALL,   //全部追加
	TRANSFER_MODE_COVER,          //覆盖
	TRANSFER_MODE_COVER_ALL,      //全部覆盖
	TRANSFER_MODE_JUMP,           //跳过
	TRANSFER_MODE_JUMP_ALL,       //全部跳过
	TRANSFER_MODE_CANCEL,         //取消传送
};


enum
{
	CLIENT_LOGIN,   //上线包
	CLIENT_GET_OUT_REQUEST,   //强制下线用户
	CLIENT_GET_OUT_REPLY,
	CLIENT_REMOTE_MESSAGE_REQUEST,
	CLIENT_REMOTE_MESSAGE_REPLY,
	CLIENT_REMOTE_MESSAGE_COMPLETE,  //远程消息到达
	CLIENT_SHUT_DOWN_REQUEST,  //远程关机请求
	CLIENT_SHUT_DOWN_REPLY,    //远程关机请求回传

	CLIENT_CMD_MANAGER_REQUEST,  //远程终端管理
	CLIENT_CMD_MANAGER_REPLY,

	CLIENT_PROCESS_MANAGER_REQUEST,  //远程进程管理请求
	CLIENT_PROCESS_MANAGER_REPLY,
	CLIENT_PROCESS_MANAGER_REFRESH_REQUEST,  //进程列表刷新

	CLIENT_WINDOW_MANAGER_REQUEST,  //远程窗口管理
	CLIENT_WINDOW_MANAGER_REPLY,
	CLIENT_WINDOW_MANAGER_REFRESH_REQUEST,

	CLIENT_REMOTE_CONTROLL_REQUEST,  //远程控制
	CLIENT_REMOTE_CONTROLL_REPLY,
	CLIENT_REMOTE_CONTROLL_FIRST_SCREEN,
	CLIENT_REMOTE_CONTROLL_NEXT_SCREEN,
	CLIENT_REMOTE_CONTROLL_CONTROL_REQUEST,
	CLIENT_REMOTE_CONTROLL_BLOCK_INPUT_REQUEST,
	CLIENT_REMOTE_CONTROLL_GET_CLIPBOARD_REQUEST,
	CLIENT_REMOTE_CONTROLL_GET_CLIPBOARD_REPLY,
	CLIENT_REMOTE_CONTROLL_SET_CLIPBOARD_REQUEST,
	CLIENT_REMOTE_CONTROLL_SET_CLIPBOARD_REPLY,

	CLIENT_FILE_MANAGER_REQUEST,   //请求磁盘数据
	CLIENT_FILE_MANAGER_REPLY,
	CLIENT_FILE_MANAGER_FILE_DATA_REQUEST,    //文件列表请求
	CLIENT_FILE_MANAGER_FILE_DATA_REPLY,
	CLIENT_FILE_MANAGER_SEND_FILE_INFORMATION,  //服务器向客户端发送一个要传送文件的文件信息(文件大小)
	CLIENT_FILE_MANAGER_TRANSFER_MODE_REQUEST,  //在客户端中发现了有同名文件
	CLIENT_FILE_MANAGER_SET_TRANSFER_MODE,
	CLIENT_FILE_MANAGER_FILE_DATA_CONTINUE,  //发数据
	CLIENT_FILE_MANAGER_FILE_DATA,

	CLIENT_AUDIO_MANAGER_REQUEST,  //语音管理
	CLIENT_AUDIO_MANAGER_REPLY,
	CLIENT_AUDIO_MANAGER_RECORD_DATA,

	CLIENT_SERVICE_MANAGER_REQUEST,   //服务管理
	CLIENT_SERVICE_MANAGER_REPLY,
	CLIENT_SERVICE_MANAGER_CONFIG_REQUEST,  //配置请求

	CLIENT_REGISTER_MANAGER_REQUEST,  //注册表管理
	CLIENT_REGISTER_MANAGER_REPLY,
	CLIENT_REGISTER_MANAGER_DATA_CONTINUE,
	CLIENT_REGISTER_MANAGER_PATH_DATA_REPLY,  //目录
	CLIENT_REGISTER_MANAGER_KEY_DATA_REPLY,   //文件

	CLIENT_GO_ON,
};